const defaultPractices=[
{icon:"📿",name:"念佛",unit:"聲",perTime:1000,goal:100000},
{icon:"🧘",name:"禪修",unit:"分鐘",perTime:30,goal:25200},
{icon:"📖",name:"讀經",unit:"次",perTime:1,goal:365},
{icon:"✍️",name:"抄經",unit:"次",perTime:1,goal:52},
{icon:"🌅",name:"早課",unit:"次",perTime:1,goal:365},
{icon:"🌙",name:"晚課",unit:"次",perTime:1,goal:365},
{icon:"🙏",name:"八十八佛",unit:"次",perTime:1,goal:365},
{icon:"🤝",name:"義工服務",unit:"小時",perTime:2,goal:120},
{icon:"🏯",name:"共修",unit:"次",perTime:1,goal:52},
{icon:"💝",name:"布施善行",unit:"次",perTime:1,goal:365}];
const days=["一","二","三","四","五","六","日"],key="myPracticeJournalCountingV2";
let state=load();
function monday(d=new Date()){let x=new Date(d),day=x.getDay(),diff=x.getDate()-day+(day===0?-6:1);x.setDate(diff);x.setHours(0,0,0,0);return x}
function ymd(d){return d.toISOString().slice(0,10)}
function add(ymd0,n){let d=new Date(ymd0+"T00:00:00");d.setDate(d.getDate()+n);return ymd(d)}
function currentYear(){return new Date(state.weekStart+"T00:00:00").getFullYear()}
function load(){try{let s=localStorage.getItem(key);if(s)return JSON.parse(s)}catch(e){}return{weekStart:ymd(monday()),goal:100000,vow:"願以今日身心，安住方法，利益眾生。",journal:"",gratitude:"",awareness:"",nextVow:"",history:{},weeks:{},practices:defaultPractices.map(p=>({...p,checks:Array(7).fill(false),note:""}))}}
function normalize(){state.practices.forEach(p=>{if(p.perTime===undefined)p.perTime=Number(p.amount||0)||1;if(!Array.isArray(p.checks))p.checks=Array(7).fill(false)});if(!state.weeks)state.weeks={};if(!state.history)state.history={}}
function save(){normalize();localStorage.setItem(key,JSON.stringify(state))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function checkedCount(p){return p.checks.filter(Boolean).length}
function weeklySubtotal(p){return checkedCount(p)*Number(p.perTime||0)}
function snapshotWeek(){normalize();state.weeks[state.weekStart]={weekStart:state.weekStart,year:currentYear(),practices:state.practices.map(p=>({name:p.name,icon:p.icon,unit:p.unit,perTime:Number(p.perTime||0),checks:[...p.checks],subtotal:weeklySubtotal(p),note:p.note||""}))};for(let d=0;d<7;d++){let date=add(state.weekStart,d);let score=state.practices.reduce((s,p)=>s+(p.checks[d]?1:0),0);state.history[date]={score,total:state.practices.length}}}
function render(){normalize();document.querySelector("#weekStart").value=state.weekStart;document.querySelector("#weekRange").textContent=`${state.weekStart} ~ ${add(state.weekStart,6)}`;["vow","journal","gratitude","awareness","nextVow"].forEach(id=>document.querySelector("#"+id).value=state[id]||"");document.querySelector("#nembutsuGoal").value=state.goal||100000;renderRows();calc();heat()}
function renderRows(){let body=document.querySelector("#practiceBody"),tpl=document.querySelector("#rowTemplate");body.innerHTML="";state.practices.forEach((p,i)=>{let r=tpl.content.firstElementChild.cloneNode(true);r.querySelector(".name").innerHTML=`${p.icon} ${esc(p.name)} <small>${esc(p.unit||"")}</small>`;r.querySelectorAll("input[type=checkbox]").forEach((b,d)=>{b.checked=!!p.checks[d];b.onchange=()=>{p.checks[d]=b.checked;snapshotWeek();save();render()}});let a=r.querySelector(".amount");a.value=p.perTime??"";a.placeholder=p.unit?`每次${p.unit}`:"每次數量";a.oninput=()=>{p.perTime=Number(a.value||0);snapshotWeek();save();render()};r.querySelector(".subtotal").textContent=`${weeklySubtotal(p).toLocaleString()} ${p.unit||""}`;let n=r.querySelector(".note");n.value=p.note||"";n.oninput=()=>{p.note=n.value;snapshotWeek();save()};r.querySelector(".remove").onclick=()=>{if(confirm(`刪除「${p.name}」？`)){state.practices.splice(i,1);snapshotWeek();save();render()}};body.appendChild(r)})}
function yearTotals(){snapshotWeek();const year=currentYear(),totals={};Object.values(state.weeks||{}).forEach(w=>{if(Number(w.year)!==year)return;(w.practices||[]).forEach(p=>{if(!totals[p.name])totals[p.name]={icon:p.icon,name:p.name,unit:p.unit,total:0,days:0};totals[p.name].total+=Number(p.subtotal||0);totals[p.name].days+=(p.checks||[]).filter(Boolean).length;totals[p.name].unit=p.unit;totals[p.name].icon=p.icon})});return totals}
function calc(){snapshotWeek();let totalCells=state.practices.length*7,done=state.practices.flatMap(p=>p.checks).filter(Boolean).length,pct=totalCells?Math.round(done/totalCells*100):0;document.querySelector("#overallPercent").textContent=pct+"%";let lotus=Array.from({length:5},(_,i)=>i<Math.round(pct/20)?"🪷":"○").join(" ");document.querySelector("#lotusLine").textContent=lotus;document.querySelector("#lotusBig").textContent=lotus;let moons=["🌑","🌒","🌓","🌔","🌕","🌖","🌗"];document.querySelector("#moon").textContent=pct>=100?"🌕🪷":moons[Math.min(6,Math.floor(pct/16))];const totals=yearTotals();let nb=totals["念佛"]?.total||0,goal=Number(state.goal||100000),np=Math.min(100,Math.round(nb/goal*100));document.querySelector("#nembutsuBar").style.width=np+"%";document.querySelector("#nembutsuText").textContent=`${nb.toLocaleString()} / ${goal.toLocaleString()} 聲（${np}%）`;let med=totals["禪修"]?.total||0;document.querySelector("#meditationBar").style.width=Math.min(100,med/25200*100)+"%";document.querySelector("#meditationText").textContent=`今年 ${(med/60).toFixed(1)} 小時`;document.querySelector("#volunteerHours").textContent=`${(totals["義工服務"]?.total||0).toLocaleString()} 小時`;let bars=document.querySelector("#bars");bars.innerHTML="";state.practices.forEach(p=>{let wk=weeklySubtotal(p),yr=totals[p.name]?.total||0,c=checkedCount(p);let row=document.createElement("div");row.className="bar-row";row.innerHTML=`<span>${p.icon} ${esc(p.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${c/7*100}%"></div></div><b>週 ${wk.toLocaleString()} / 年 ${yr.toLocaleString()} ${esc(p.unit||"")}</b>`;bars.appendChild(row)})}
function heat(){let wrap=document.querySelector("#heatmap");wrap.innerHTML="";let year=currentYear(),s=new Date(`${year}-01-01T00:00:00`),e=new Date(`${year}-12-31T00:00:00`);for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1)){let date=ymd(d),h=state.history[date],r=h&&h.total?h.score/h.total:0,lv=r===0?0:r<.25?1:r<.5?2:r<.85?3:4;let cell=document.createElement("span");cell.className=`day lv${lv}`;cell.title=`${date}：${h?.score||0}/${h?.total||state.practices.length}`;wrap.appendChild(cell)}}
function csv(){snapshotWeek();save();let headers=["weekStart","practice","icon","unit","perTime",...days.map(d=>"day_"+d),"weeklySubtotal","yearTotal","note","vow","journal","gratitude","awareness","nextVow"];let totals=yearTotals();let rows=state.practices.map(p=>[state.weekStart,p.name,p.icon,p.unit,p.perTime,...p.checks,weeklySubtotal(p),totals[p.name]?.total||0,p.note||"",state.vow||"",state.journal||"",state.gratitude||"",state.awareness||"",state.nextVow||""]);let text=[headers,...rows].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n");let blob=new Blob(["\ufeff"+text],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`我的修行手帳_${state.weekStart}.csv`;a.click();URL.revokeObjectURL(a.href)}
function parse(line){let out=[],cur="",q=false;for(let i=0;i<line.length;i++){let ch=line[i],nx=line[i+1];if(ch=='"'&&q&&nx=='"'){cur+='"';i++}else if(ch=='"')q=!q;else if(ch==","&&!q){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out}
function importCsv(file){let rd=new FileReader();rd.onload=()=>{let lines=rd.result.replace(/^\ufeff/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return alert("CSV 沒有資料");let rows=lines.slice(1).map(parse);state.weekStart=rows[0][0]||state.weekStart;state.practices=rows.map(r=>({name:r[1],icon:r[2],unit:r[3],perTime:Number(r[4]||0),checks:r.slice(5,12).map(v=>v==="true"),note:r[14]||""}));state.vow=rows[0][15]||"";state.journal=rows[0][16]||"";state.gratitude=rows[0][17]||"";state.awareness=rows[0][18]||"";state.nextVow=rows[0][19]||"";snapshotWeek();save();render()};rd.readAsText(file,"utf-8")}
function sample(){state.practices.forEach((p,i)=>{p.checks=p.checks.map((_,d)=>(d+i)%3!==0);if(p.name==="念佛")p.perTime=1000;if(p.name==="禪修")p.perTime=40;if(p.name==="義工服務")p.perTime=2});state.journal="今天坐香時雜念較多，但有一次清楚看見自己想被肯定的心，於是回到呼吸與方法。";state.gratitude="感謝道場、善知識，也感謝今天願意練習的自己。";state.awareness="不要把定課變成表現，修行是回來照顧自己的心。";state.nextVow="下週穩穩完成晚課，不急著求成果。";snapshotWeek();save();render()}
document.querySelector("#weekStart").onchange=e=>{snapshotWeek();save();state.weekStart=e.target.value;let wk=state.weeks[state.weekStart];if(wk){wk.practices.forEach(saved=>{let p=state.practices.find(x=>x.name===saved.name);if(p){p.checks=[...saved.checks];p.perTime=saved.perTime;p.note=saved.note||""}})}snapshotWeek();save();render()};["vow","journal","gratitude","awareness","nextVow"].forEach(id=>document.querySelector("#"+id).oninput=e=>{state[id]=e.target.value;save()});document.querySelector("#nembutsuGoal").oninput=e=>{state.goal=Number(e.target.value||100000);save();calc()};document.querySelector("#saveBtn").onclick=()=>{snapshotWeek();save();alert("已儲存到瀏覽器，並更新年度累計。")};document.querySelector("#clearBtn").onclick=()=>{if(confirm("清除本週勾選與備註？每次預計數量會保留。")){state.practices.forEach(p=>{p.checks=Array(7).fill(false);p.note=""});snapshotWeek();save();render()}};document.querySelector("#exportBtn").onclick=csv;document.querySelector("#importFile").onchange=e=>e.target.files[0]&&importCsv(e.target.files[0]);document.querySelector("#sampleBtn").onclick=sample;let dialog=document.querySelector("#dialog");document.querySelector("#addPractice").onclick=()=>dialog.showModal();document.querySelector("#confirmAdd").onclick=e=>{e.preventDefault();let icon=document.querySelector("#newIcon").value||"🌱",name=document.querySelector("#newName").value.trim(),unit=document.querySelector("#newUnit").value.trim();if(!name)return alert("請輸入名稱");state.practices.push({icon,name,unit,perTime:1,checks:Array(7).fill(false),note:""});document.querySelector("#newName").value="";document.querySelector("#newUnit").value="";dialog.close();snapshotWeek();save();render()};normalize();snapshotWeek();save();render();
